l_french:
 anb_settings.1.t:0 "Bienvenue dans :\n£settings_main_bg£"
 anb_settings.1.d:2 "§L                                              La Mise à jour de l'Empire Final                EU4 version 1.37.5"
 anb_settings.1.a:0 "£settings_button_regions_menu£"
 anb_settings.1.b:0 "£settings_button_conquerors_menu£"
 anb_settings.1.bx:0 "£settings_button_conquerors_menu_g£"
 anb_settings.1.c:0 "£settings_button_achievements_off£"
 anb_settings.1.cx:0 "£settings_button_achievements_on£"
 anb_settings.1.s:0 "£settings_button_start_game£"
 anb_settings.1.empty:0 "£event_button_settings_empty£"

 anb_settings.2.t:0 "Grands Conquérants\n£settings_conqueror_bg£"
 anb_settings.2.d:0 ""
 anb_settings.2.a:0 "£settings_button_no_conqueror_g£"
 anb_settings.2.ax:0 "£settings_button_no_conqueror£"
 anb_settings.2.b:0 "£settings_button_conqueror_g£"
 anb_settings.2.bx:0 "£settings_button_conqueror£"
 anb_settings.2.c:0 "£settings_button_mythical_g£"
 anb_settings.2.cx:0 "£settings_button_mythical£"
 anb_settings.2.dd:0 "£settings_button_conqueror_variance_off£"
 anb_settings.2.ddx:0 "£settings_button_conqueror_variance_on£"
 anb_settings.2.e:0 "£settings_button_conqueror_delay_off£"
 anb_settings.2.ex:0 "£settings_button_conqueror_delay_on£"
 anb_settings.2.x:0 "£settings_button_back_to_menu_2£"

 anb_settings.3.t:0 "£settings_regions_bg£\n    [Root.GetSettingsNorthAelantir]\n    [Root.GetSettingsCannor]\n    [Root.GetSettingsForbiddenPlains]\n    [Root.GetSettingsWestSerpentspine]\n    [Root.GetSettingsHaless]\n    [Root.GetSettingsDeepwoods]\n    [Root.GetSettingsBulwar]\n    [Root.GetSettingsEastSerpentspine]\n    [Root.GetSettingsRahen]\n    [Root.GetSettingsNorthSarhal]\n    [Root.GetSettingsInsyaa]\n    [Root.GetSettingsSouthAelantir]\n    [Root.GetSettingsSouthSarhal]\n    [Root.GetSettingsEastSarhal]\n    [Root.GetSettingsGozenguun]"
 anb_settings.3.d:0 "\n\n\n\n[Root.GetSettingsAlertRed][Root.GetSettingsAlertOrange]"
 anb_settings.3.a:0 "£settings_button_all££settings_alert_none£"
 anb_settings.3.ax:0 "£settings_button_all_x££settings_alert_none£"
 anb_settings.3.b:0 "£settings_button_north_aelantir££settings_alert_none£"
 anb_settings.3.bx:0 "£settings_button_north_aelantir_x£[Root.GetSettingsAlertNorthAelantir]"
 anb_settings.3.c:0 "£settings_button_south_aelantir££settings_alert_none£"
 anb_settings.3.cx:0 "£settings_button_south_aelantir_x£[Root.GetSettingsAlertSouthAelantir]"
 anb_settings.3.dd:0 "£settings_button_cannor££settings_alert_none£"
 anb_settings.3.ddx:0 "£settings_button_cannor_x£[Root.GetSettingsAlertCannor]"
 anb_settings.3.e:0 "£settings_button_deepwoods££settings_alert_none£"
 anb_settings.3.ex:0 "£settings_button_deepwoods_x£[Root.GetSettingsAlertDeepwoods]"
 anb_settings.3.f:0 "£settings_button_bulwar££settings_alert_none£"
 anb_settings.3.fx:0 "£settings_button_bulwar_x£[Root.GetSettingsAlertBulwar]"
 anb_settings.3.g:0 "£settings_button_north_sarhal££settings_alert_none£"
 anb_settings.3.gx:0 "£settings_button_north_sarhal_x£[Root.GetSettingsAlertNorthSarhal]"
 anb_settings.3.h:0 "£settings_button_south_sarhal££settings_alert_none£"
 anb_settings.3.hx:0 "£settings_button_south_sarhal_x£[Root.GetSettingsAlertSouthSarhal]"
 anb_settings.3.i:0 "£settings_button_east_sarhal££settings_alert_none£"
 anb_settings.3.ix:0 "£settings_button_east_sarhal_x£[Root.GetSettingsAlertEastSarhal]"
 anb_settings.3.j:0 "£settings_button_west_serpentspine££settings_alert_none£"
 anb_settings.3.jx:0 "£settings_button_west_serpentspine_x£[Root.GetSettingsAlertWestSerpentspine]"
 anb_settings.3.k:0 "£settings_button_east_serpentspine££settings_alert_none£"
 anb_settings.3.kx:0 "£settings_button_east_serpentspine_x£[Root.GetSettingsAlertEastSerpentspine]"
 anb_settings.3.l:0 "£settings_button_forbidden_plains££settings_alert_none£"
 anb_settings.3.lx:0 "£settings_button_forbidden_plains_x£[Root.GetSettingsAlertForbiddenPlains]"
 anb_settings.3.m:0 "£settings_button_rahen££settings_alert_none£"
 anb_settings.3.mx:0 "£settings_button_rahen_x£[Root.GetSettingsAlertRahen]"
 anb_settings.3.n:0 "£settings_button_haless££settings_alert_none£"
 anb_settings.3.nx:0 "£settings_button_haless_x£[Root.GetSettingsAlertHaless]"
 anb_settings.3.o:0 "£settings_button_gozenguun££settings_alert_none£"
 anb_settings.3.ox:0 "£settings_button_gozenguun_x£[Root.GetSettingsAlertGozenguun]"
 anb_settings.3.p:0 "£settings_button_insyaa££settings_alert_none£"
 anb_settings.3.px:0 "£settings_button_insyaa_x£[Root.GetSettingsAlertInsyaa]"
 anb_settings.3.x:0 "£settings_button_back_to_menu£"

 #custom loc
 settings_cannor_yes:0 "£settings_cannor£"
 settings_north_aelantir_yes:0 "£settings_north_aelantir£"
 settings_forbidden_plains_yes:0 "£settings_forbidden_plains£"
 settings_bulwar_yes:0 "£settings_bulwar£"
 settings_deepwoods_yes:0 "£settings_deepwoods£"
 settings_east_serpentspine_yes:0 "£settings_east_serpentspine£"
 settings_haless_yes:0 "£settings_haless£"
 settings_gozenguun_yes:0 "£settings_gozenguun£"
 settings_north_sarhal_yes:0 "£settings_north_sarhal£"
 settings_rahen_yes:0 "£settings_rahen£"
 settings_west_serpentspine_yes:0 "£settings_west_serpentspine£"
 settings_insyaa_yes:0 "£settings_insyaa£"
 settings_south_aelantir_yes:0 "£settings_south_aelantir£"
 settings_south_sarhal_yes:0 "£settings_south_sarhal£"
 settings_east_sarhal_yes:0 "£settings_east_sarhal£"
 settings_no:0 ""

 settings_alert_orange:0 "£settings_alert_orange£"
 settings_alert_red:0 "£settings_alert_red£"
 settings_alert_red_orange:0 "£settings_alert_red_orange£"
 settings_alert_none:0 "£settings_alert_none£"

 settings_alert_orange_main:0 "£settings_alert_orange_main£"
 settings_alert_red_main:0 "£settings_alert_red_main£\n"
 settings_alert_none_main:0 ""

 #tooltip
 settings_achievement_tt:0 "Désactiver les succès peut entraîner une amélioration (très) mineure des performances du jeu"
 settings_achievement_disabled_tt:0 "§RLes succès ne peuvent pas être activés en multijoueur§!"

 no_conquerors_tooltip:0 "§G« La normalité est une route pavée. Elle est confortable à parcourir, mais aucune fleur n'y pousse. »§!\n\nPour ceux qui recherchent une expérience Anbennar standard."
 great_conqueror_tooltip:0 "§O« Les lâches se dérobent face aux défis, les faibles les fuient, mais les guerriers leur font un clin d'œil. »§!\n\nCette option activera les §YGrands Conquérants§! pour une partie plus difficile."
 mythical_conqueror_tooltip:0 "§R« Connais-toi toi-même, connais ton ennemi. Mille batailles, mille victoires. »§!\n\nPour ceux qui souhaitent danser avec le danger."
 random_conqueror_targets_tooltip:0 "§O« Le changement est inévitable. La croissance est optionnelle. »§!\n\nActive les §YConquérants Variants§! pour des défis uniques à surmonter."
 delayed_conqueror_tooltip:0 "§O« La nature ne se presse pas, pourtant tout s'accomplit. »§!\n\nDésactive les §YGrands Conquérants§! jusqu'à l'§YÈre de l'Effondrement§!."

 settings_conquerors_tt:0 "§YGrands Conquérants§!\nDes pays IA choisis dynamiquement recevront des bonus pour les aider à consolider leurs environs, afin de fournir des adversaires plus difficiles en milieu et fin de partie."
 settings_regions_tt:0 "§YDésactivation des Régions§!\nDésactiver certaines parties du monde vous permettra d'améliorer les performances du jeu."
 settings_needs_rom_dlc_tt:0 "§RCette fonctionnalité nécessite le DLC Rights of Man§!"
 institutions_warning_tt:0 "£icon_settings_alert_red£ §RDésactiver Cannor empêchera certaines Institutions d'apparaître correctement§!\n"
 tag_need_this_region_tt:0 "£icon_settings_alert_orange£ §y[Root.GetName] pourrait avoir du contenu lié à cette région§!"
 tag_in_this_region_tt:0 "£icon_settings_alert_red£ §RLa capitale de [Root.GetName] est dans cette région§!\n"
 disable_region_tt:0 "Désactive cette région pour améliorer les performances du jeu.\n---------------------------\n"
 disable_all_region_tt:0 "Désactive toutes les régions."
 settings_wont_be_available_tt:0 "§RLes paramètres ne sont disponibles qu'au début de la partie, vous ne pourrez plus y accéder par la suite.§!"
 settings_regions_are_gonna_get_removed_tt:0 "£icon_settings_alert_red£ §RLes régions désactivées seront retirées du jeu, et vous ne pourrez pas les rajouter ultérieurement. Cette action peut faire laguer le jeu pendant quelques secondes.§!"

 #Great Conqueror event loca
 great_conqueror.2.t:0 "Un Roi-Liche s'élève"
 great_conqueror.2.d:0 "« Je me jette à votre visage. Vous voyez tout ce que je suis, et je suis parfait. »\n-Catéchisme de Theknial, Dernière Page.\n\nBeaucoup ont osé tenter les vils rituels d'ascension par le passé, bien que peu aient réussi à profaner la mortalité elle-même et à atteindre la Lichéité. On ne peut supporter une telle cruauté sans une volonté de fer et un cœur de goudron. Mais cela n'a pas empêché le [From.Monarch.GetTitle] de [From.GetName] de rejeter la pureté et de devenir un être de pur mal : une véritable Liche.\n\nDes hordes de zombies, de squelettes et d'horreurs que le Roi-Liche [From.Monarch.GetName] a rassemblées marchent sur le monde, et nous n'avons vu que le commencement d'un nouveau domaine nécromantique."
 great_conqueror.2.a:0 "Nous devons prendre sur nous de réparer leurs torts."
 great_conqueror_2_tt:0 "Un §YRoi-Liche§! s'est élevé à [From.GetName]."

 lich_king_tt:0 "§RLes armées de morts-vivants de [From.GetName] vont déferler sur Halann. Nous devons nous préparer.§!"
